// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf-DAxWT3TpUCJCYATFYxYbxX1AdUoYIs',
    appId: '1:303512308113:web:301f853358a5c9214eb230',
    messagingSenderId: '303512308113',
    projectId: 'kashf-77bfd',
    authDomain: 'kashf-77bfd.firebaseapp.com',
    storageBucket: 'kashf-77bfd.appspot.com',
    measurementId: 'G-PDHEXJJC6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvawYF1b8bVwAFPtcV39SIPsbRQ6j05w',
    appId: '1:303512308113:android:0efc8ae478a917f94eb230',
    messagingSenderId: '303512308113',
    projectId: 'salon-app-df8bd',
    storageBucket: 'kashf-77bfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KCHEu4CNuEEsjcJMxS3OHtLTBlJfjVo',
    appId: '1:303512308113:ios:3ca8556b8418512d4eb230',
    messagingSenderId: '303512308113',
    projectId: 'kashf-77bfd',
    storageBucket: 'kashf-77bfd.appspot.com',
    iosBundleId: 'com.ahmedsherifandtahakashf.kashf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8KCHEu4CNuEEsjcJMxS3OHtLTBlJfjVo',
    appId: '1:303512308113:ios:493e6347919228474eb230',
    messagingSenderId: '303512308113',
    projectId: 'kashf-77bfd',
    storageBucket: 'kashf-77bfd.appspot.com',
    iosBundleId: 'com.ahmedsherifandtahakashf.kashf.RunnerTests',
  );
}
